INFO 2016-08-28 13:37:01,198 managers 25912 140298854348608 Threshold date for cancellation: 2016-07-27 00:00:00+00:00
ERROR 2016-08-28 13:37:01,218 managers 25912 140298854348608 Could not match braintree state for user BraintreeUser: {User : ActiveFarFromExpiry, CustomerID: active_far_from_expiry_customer, SubscriptionID: ActiveFarSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/managers.py", line 18, in match_braintree_state
    subscription = SubscriptionManager.fetch_subscription_from_braintree(user)
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 194, in fetch_subscription_from_braintree
    str(braintree_customer) + "!")
BraintreeError: Could not fetch state for user ActiveFarFromExpiry with braintree details BraintreeUser: {User : ActiveFarFromExpiry, CustomerID: active_far_from_expiry_customer, SubscriptionID: ActiveFarSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}!
ERROR 2016-08-28 13:37:01,219 managers 25912 140298854348608 Could not match braintree state for user BraintreeUser: {User : ActiveNotPendingCancel, CustomerID: active_customer, SubscriptionID: ActiveNotCancelPendingSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/managers.py", line 18, in match_braintree_state
    subscription = SubscriptionManager.fetch_subscription_from_braintree(user)
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 194, in fetch_subscription_from_braintree
    str(braintree_customer) + "!")
BraintreeError: Could not fetch state for user ActiveNotPendingCancel with braintree details BraintreeUser: {User : ActiveNotPendingCancel, CustomerID: active_customer, SubscriptionID: ActiveNotCancelPendingSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}!
ERROR 2016-08-28 13:37:02,007 views 25912 140298854348608 Failed to move subscription for test123 to pending cancel.
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/views.py", line 85, in post
    SubscriptionManager.request_cancel(braintree_user)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 107, in new_mocked_method
    return call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 45, in __call__
    return invoc(*params, **named_params)
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 92, in __call__
    return matching_invocation.answer_first()
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 51, in answer_first
    return self.answers[0].answer() if self.answers is not None else None
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 205, in answer
    return a.answer()
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 213, in answer
    raise self.exception
BraintreeError
ERROR 2016-08-28 13:37:06,694 views 25912 140298854348608 Failed to subscribed user test123
INFO 2016-08-28 13:37:11,707 views 25912 140298854348608 New subscription created for user test123
ERROR 2016-08-28 13:43:42,916 subscription_manager 26087 140007560656704 Could not fetch Braintree state for user: ActiveFarFromExpiry
ERROR 2016-08-28 13:43:42,917 subscription_manager 26087 140007560656704 Could not fetch Braintree state for user: ActiveNotPendingCancel
ERROR 2016-08-28 13:43:45,776 subscription_manager 26087 140007560656704 No braintree account associated with user NotInitialized. Must create one!
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 27, in fetch_braintree_user
    braintree_user = BraintreeUser.objects.get(user=user)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: BraintreeUser matching query does not exist.
ERROR 2016-08-28 13:43:52,860 subscription_manager 26087 140007560656704 No braintree account associated with user NotInitialized. Must create one!
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 27, in fetch_braintree_user
    braintree_user = BraintreeUser.objects.get(user=user)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: BraintreeUser matching query does not exist.
INFO 2016-08-28 13:44:01,444 managers 26127 140073088280384 Threshold date for cancellation: 2016-07-27 00:00:00+00:00
ERROR 2016-08-28 13:44:01,464 managers 26127 140073088280384 Could not match braintree state for user BraintreeUser: {User : ActiveFarFromExpiry, CustomerID: active_far_from_expiry_customer, SubscriptionID: ActiveFarSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/managers.py", line 18, in match_braintree_state
    subscription = SubscriptionManager.fetch_subscription_from_braintree(user)
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 194, in fetch_subscription_from_braintree
    str(braintree_customer) + "!")
BraintreeError: Could not fetch state for user ActiveFarFromExpiry with braintree details BraintreeUser: {User : ActiveFarFromExpiry, CustomerID: active_far_from_expiry_customer, SubscriptionID: ActiveFarSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}!
ERROR 2016-08-28 13:44:01,465 managers 26127 140073088280384 Could not match braintree state for user BraintreeUser: {User : ActiveNotPendingCancel, CustomerID: active_customer, SubscriptionID: ActiveNotCancelPendingSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/managers.py", line 18, in match_braintree_state
    subscription = SubscriptionManager.fetch_subscription_from_braintree(user)
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 194, in fetch_subscription_from_braintree
    str(braintree_customer) + "!")
BraintreeError: Could not fetch state for user ActiveNotPendingCancel with braintree details BraintreeUser: {User : ActiveNotPendingCancel, CustomerID: active_customer, SubscriptionID: ActiveNotCancelPendingSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}!
INFO 2016-08-28 13:49:10,628 views 26308 140402186360640 Password reset requested for user AnonymousUser
INFO 2016-08-28 13:49:10,962 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:11,884 views 26308 140402186360640 New user RegistrationSerializer(data={u'username': u'test1', u'password1': u'GBG18H42,]bb', u'first_name': u'michael', u'last_name': u'kilian', u'password2': u'GBG18H42,]bb', u'email': u'test@fake.com'}):
    username = CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, validators=[<django.core.validators.RegexValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    email = EmailField(required=True)
    first_name = CharField(max_length=30, required=True)
    last_name = CharField(max_length=30, required=True)
    password1 = CharField(validators=[<restful_auth.validators.LengthValidator object>, <restful_auth.validators.CommonSequenceValidator object>, <restful_auth.validators.ComplexityValidator object>, <restful_auth.validators.DictionaryValidator object>], write_only=True)
    password2 = CharField(write_only=True) registered!
INFO 2016-08-28 13:49:12,328 views 26308 140402186360640 User test updated their details.
INFO 2016-08-28 13:49:12,384 views 26308 140402186360640 User test updated their details.
INFO 2016-08-28 13:49:12,438 views 26308 140402186360640 User test updated their details.
INFO 2016-08-28 13:49:12,637 views 26308 140402186360640 User AnonymousUser has confirmed their email.
INFO 2016-08-28 13:49:12,868 views 26308 140402186360640 Password reset for test confirmed.
INFO 2016-08-28 13:49:12,924 managers 26308 140402186360640 Threshold date for cancellation: 2016-07-27 00:00:00+00:00
WARNING 2016-08-28 13:49:12,944 __init__ 26308 140402186360640 /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1282: RuntimeWarning: DateTimeField BraintreeUser.expiry_date received a naive datetime (2016-07-24 00:02:00) while time zone support is active.
  RuntimeWarning)

ERROR 2016-08-28 13:49:12,945 subscription_manager 26308 140402186360640 Could not fetch Braintree state for user: ActiveFarFromExpiry
ERROR 2016-08-28 13:49:12,945 managers 26308 140402186360640 Could not match braintree state for user BraintreeUser: {User : ActiveFarFromExpiry, CustomerID: active_far_from_expiry_customer, SubscriptionID: ActiveFarSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/managers.py", line 18, in match_braintree_state
    subscription = SubscriptionManager.fetch_subscription_from_braintree(user)
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 194, in fetch_subscription_from_braintree
    str(braintree_customer) + "!")
BraintreeError: Could not fetch state for user ActiveFarFromExpiry with braintree details BraintreeUser: {User : ActiveFarFromExpiry, CustomerID: active_far_from_expiry_customer, SubscriptionID: ActiveFarSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}!
ERROR 2016-08-28 13:49:12,946 subscription_manager 26308 140402186360640 Could not fetch Braintree state for user: ActiveNotPendingCancel
ERROR 2016-08-28 13:49:12,946 managers 26308 140402186360640 Could not match braintree state for user BraintreeUser: {User : ActiveNotPendingCancel, CustomerID: active_customer, SubscriptionID: ActiveNotCancelPendingSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/managers.py", line 18, in match_braintree_state
    subscription = SubscriptionManager.fetch_subscription_from_braintree(user)
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 194, in fetch_subscription_from_braintree
    str(braintree_customer) + "!")
BraintreeError: Could not fetch state for user ActiveNotPendingCancel with braintree details BraintreeUser: {User : ActiveNotPendingCancel, CustomerID: active_customer, SubscriptionID: ActiveNotCancelPendingSubID, PaymentMethodToken: None, Active: False, PendingCancel: True, ExpiryDate: None}!
WARNING 2016-08-28 13:49:12,947 __init__ 26308 140402186360640 /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1282: RuntimeWarning: DateTimeField BraintreeUser.expiry_date received a naive datetime (2016-11-02 00:02:00) while time zone support is active.
  RuntimeWarning)

WARNING 2016-08-28 13:49:12,947 __init__ 26308 140402186360640 /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1282: RuntimeWarning: DateTimeField BraintreeUser.expiry_date received a naive datetime (2016-10-03 00:02:00) while time zone support is active.
  RuntimeWarning)

INFO 2016-08-28 13:49:12,960 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
ERROR 2016-08-28 13:49:13,734 views 26308 140402186360640 Failed to move subscription for test123 to pending cancel.
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/views.py", line 85, in post
    SubscriptionManager.request_cancel(braintree_user)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 107, in new_mocked_method
    return call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 45, in __call__
    return invoc(*params, **named_params)
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 92, in __call__
    return matching_invocation.answer_first()
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 51, in answer_first
    return self.answers[0].answer() if self.answers is not None else None
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 205, in answer
    return a.answer()
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 213, in answer
    raise self.exception
BraintreeError
INFO 2016-08-28 13:49:13,745 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:14,525 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
ERROR 2016-08-28 13:49:15,251 subscription_manager 26308 140402186360640 No braintree account associated with user NotInitialized. Must create one!
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 27, in fetch_braintree_user
    braintree_user = BraintreeUser.objects.get(user=user)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: BraintreeUser matching query does not exist.
INFO 2016-08-28 13:49:15,264 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:15,997 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:16,719 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:17,449 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
ERROR 2016-08-28 13:49:18,311 views 26308 140402186360640 Failed to subscribed user test123
INFO 2016-08-28 13:49:18,320 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:19,033 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:19,917 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:20,636 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
ERROR 2016-08-28 13:49:21,519 subscription_manager 26308 140402186360640 No braintree account associated with user NotInitialized. Must create one!
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 27, in fetch_braintree_user
    braintree_user = BraintreeUser.objects.get(user=user)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: BraintreeUser matching query does not exist.
INFO 2016-08-28 13:49:21,522 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:22,246 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:23,135 views 26308 140402186360640 New subscription created for user test123
INFO 2016-08-28 13:49:23,152 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:23,923 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:24,787 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:25,652 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:26,359 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:27,330 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:28,241 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:28,955 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:29,826 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:30,682 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:31,414 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:32,283 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:33,205 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:33,944 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:34,821 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:35,701 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:36,454 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:37,310 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:43,236 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:43,969 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:44,910 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:45,984 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
ERROR 2016-08-28 13:49:46,732 views 26308 140402186360640 Failed to change user test123 payment method
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/views.py", line 153, in post
    SubscriptionManager.change_payment_method(braintree_user,payment_method_nonce)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 107, in new_mocked_method
    return call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mockito/mocking.py", line 45, in __call__
    return invoc(*params, **named_params)
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 92, in __call__
    return matching_invocation.answer_first()
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 51, in answer_first
    return self.answers[0].answer() if self.answers is not None else None
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 205, in answer
    return a.answer()
  File "/usr/local/lib/python2.7/dist-packages/mockito/invocation.py", line 213, in answer
    raise self.exception
BraintreeError
INFO 2016-08-28 13:49:46,743 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:47,462 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
INFO 2016-08-28 13:49:48,221 connectionpool 26308 140402186360640 Starting new HTTPS connection (1): api.sandbox.braintreegateway.com
ERROR 2016-08-28 13:49:49,131 subscription_manager 26308 140402186360640 No braintree account associated with user UserNotInitialized. Must create one!
Traceback (most recent call last):
  File "/home/michael/DentestRevised/server/subscriptions/subscription_manager.py", line 27, in fetch_braintree_user
    braintree_user = BraintreeUser.objects.get(user=user)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: BraintreeUser matching query does not exist.
WARNING 2016-08-28 13:49:52,322 generic_views 26308 140402186360640 Non-staff user attempted to create a subtopic. Username : test_token_free
WARNING 2016-08-28 13:49:52,325 generic_views 26308 140402186360640 Non-staff user attempted to create a topic. Username : test_token_premium
WARNING 2016-08-28 13:49:53,882 generic_views 26308 140402186360640 Non-staff user attempted to create a topic. Username : test_token_free
WARNING 2016-08-28 13:49:53,884 generic_views 26308 140402186360640 Non-staff user attempted to create a topic. Username : test_token_premium
ERROR 2016-08-28 16:18:38,078 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:18:38,078 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:18:38,273 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:18:38,273 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:18:42,959 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:18:42,959 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:18:45,253 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:18:45,253 base 29644 139701727999744 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:19:29,838 base 29707 140420594370304 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:19:29,838 base 29707 140420594370304 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:19:35,431 base 29707 140420594370304 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
ERROR 2016-08-28 16:19:35,431 base 29707 140420594370304 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
WARNING 2016-08-28 16:20:16,258 base 29742 139667541702400 Not Found: /
WARNING 2016-08-28 16:20:19,894 base 29742 139667541702400 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:20:19,903 base 29742 139667530950400 Not Found: /static/admin/css/login.css
ERROR 2016-08-28 16:20:21,517 base 29742 139667541702400 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-08-28 16:21:34,625 base 29811 140020262606592 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-08-28 16:26:36,123 base 29948 140117488588544 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-08-28 16:26:37,596 base 29948 140117488588544 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-08-28 16:28:32,228 base 30066 140555983374080 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
WARNING 2016-08-28 16:33:07,507 base 30267 140610109900544 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:33:07,532 base 30267 140610098099968 Not Found: /static/admin/css/dashboard.css
WARNING 2016-08-28 16:33:19,695 base 30267 140610098099968 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:33:19,699 base 30267 140610109900544 Not Found: /static/admin/css/dashboard.css
WARNING 2016-08-28 16:36:50,239 base 30409 140659496875776 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:36:50,240 base 30409 140659485075200 Not Found: /static/admin/css/dashboard.css
WARNING 2016-08-28 16:36:51,703 base 30409 140659485075200 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:36:51,710 base 30409 140659496875776 Not Found: /static/admin/css/dashboard.css
WARNING 2016-08-28 16:38:09,198 base 30466 140712619427584 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:38:09,210 base 30466 140712608675584 Not Found: /static/admin/css/dashboard.css
WARNING 2016-08-28 16:38:11,789 base 30466 140712608675584 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:38:11,795 base 30466 140712619427584 Not Found: /static/admin/css/dashboard.css
WARNING 2016-08-28 16:38:13,657 base 30466 140712619427584 Not Found: /static/admin/css/base.css
WARNING 2016-08-28 16:38:13,669 base 30466 140712389637888 Not Found: /static/django_tinymce/init_tinymce.js
WARNING 2016-08-28 16:38:13,685 base 30466 140712599758592 Not Found: /static/tiny_mce/tiny_mce.js
WARNING 2016-08-28 16:38:13,879 base 30466 140712608675584 Not Found: /static/tiny_mce/tiny_mce.js
WARNING 2016-08-28 16:38:13,889 base 30466 140712619427584 Not Found: /static/django_tinymce/init_tinymce.js
WARNING 2016-08-28 16:40:04,838 base 30599 139867843557120 Not Found: /subtopic/
WARNING 2016-08-28 16:40:15,976 base 30599 139867843557120 Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING 2016-08-28 16:40:15,996 base 30599 139867843557120 Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING 2016-08-28 16:40:15,997 base 30599 139867757475584 Not Found: /static/rest_framework/css/prettify.css
WARNING 2016-08-28 16:40:16,002 base 30599 139867749082880 Not Found: /static/rest_framework/css/default.css
WARNING 2016-08-28 16:40:16,016 base 30599 139867723904768 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:40:16,018 base 30599 139867740690176 Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
WARNING 2016-08-28 16:40:16,020 base 30599 139867732297472 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:40:16,045 base 30599 139867757475584 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:40:16,065 base 30599 139867757475584 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:40:16,153 base 30599 139867757475584 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:40:16,213 base 30599 139867757475584 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:42:09,975 base 30695 140578997245696 Not Found: /static/rest_framework/css/default.css
WARNING 2016-08-28 16:42:09,976 base 30695 140578988852992 Not Found: /static/rest_framework/css/prettify.css
WARNING 2016-08-28 16:42:09,986 base 30695 140578775889664 Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING 2016-08-28 16:42:09,996 base 30695 140578767496960 Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING 2016-08-28 16:42:10,000 base 30695 140578759104256 Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
WARNING 2016-08-28 16:42:10,015 base 30695 140579008784128 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:42:10,016 base 30695 140578750711552 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:42:10,045 base 30695 140578997245696 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:42:10,073 base 30695 140578997245696 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:42:10,091 base 30695 140578997245696 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:42:12,220 base 30695 140578997245696 Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING 2016-08-28 16:42:12,227 base 30695 140578750711552 Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING 2016-08-28 16:42:12,236 base 30695 140579008784128 Not Found: /static/rest_framework/css/prettify.css
WARNING 2016-08-28 16:42:12,251 base 30695 140578997245696 Not Found: /static/rest_framework/css/default.css
WARNING 2016-08-28 16:42:12,255 base 30695 140578750711552 Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
WARNING 2016-08-28 16:42:12,258 base 30695 140578775889664 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:42:12,275 base 30695 140579008784128 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:42:12,280 base 30695 140578997245696 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:42:12,303 base 30695 140578750711552 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:42:12,321 base 30695 140578750711552 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:42:12,332 base 30695 140578750711552 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:43:42,236 base 30795 140080022812416 Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
WARNING 2016-08-28 16:43:42,240 base 30795 140080234686208 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:43:42,242 base 30795 140080246224640 Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING 2016-08-28 16:43:42,247 base 30795 140080014419712 Not Found: /static/rest_framework/css/default.css
WARNING 2016-08-28 16:43:42,257 base 30795 140080006027008 Not Found: /static/rest_framework/css/prettify.css
WARNING 2016-08-28 16:43:42,271 base 30795 140079997634304 Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING 2016-08-28 16:43:42,288 base 30795 140080246224640 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:43:42,290 base 30795 140080022812416 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:43:42,299 base 30795 140080234686208 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:43:42,342 base 30795 140080022812416 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:43:42,351 base 30795 140080022812416 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:44:59,776 base 30872 140581916845824 Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING 2016-08-28 16:44:59,778 base 30872 140581908453120 Not Found: /static/rest_framework/css/prettify.css
WARNING 2016-08-28 16:44:59,779 base 30872 140581927859968 Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING 2016-08-28 16:44:59,782 base 30872 140581900060416 Not Found: /static/rest_framework/css/default.css
WARNING 2016-08-28 16:44:59,790 base 30872 140581891667712 Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
WARNING 2016-08-28 16:44:59,809 base 30872 140581916845824 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:44:59,812 base 30872 140581874882304 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:44:59,816 base 30872 140581883275008 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:44:59,866 base 30872 140581874882304 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:44:59,877 base 30872 140581874882304 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:48:47,010 base 30872 140581874882304 Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING 2016-08-28 16:48:47,015 base 30872 140581883275008 Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING 2016-08-28 16:48:47,023 base 30872 140581900060416 Not Found: /static/rest_framework/css/prettify.css
WARNING 2016-08-28 16:48:47,032 base 30872 140581874882304 Not Found: /static/rest_framework/css/default.css
WARNING 2016-08-28 16:48:47,038 base 30872 140581900060416 Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
WARNING 2016-08-28 16:48:47,045 base 30872 140581874882304 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:48:47,050 base 30872 140581883275008 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:48:47,061 base 30872 140581900060416 Not Found: /static/rest_framework/js/default.js
WARNING 2016-08-28 16:48:47,079 base 30872 140581900060416 Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING 2016-08-28 16:48:47,093 base 30872 140581900060416 Not Found: /static/rest_framework/js/prettify-min.js
WARNING 2016-08-28 16:48:47,101 base 30872 140581900060416 Not Found: /static/rest_framework/js/default.js
