WARNING 2016-10-01 13:53:33,474 base 1897 139774607832960 Not Found: /
WARNING 2016-10-01 13:53:34,305 base 1903 139774607832960 Not Found: /favicon.ico
ERROR 2016-10-01 13:53:38,874 base 1903 139774607832960 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 361, in login
    return login(request, **defaults)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 50, in login
    current_site = get_current_site(request)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
    return Site.objects.get_current()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 54, in get_current
    current_site = self.get(pk=sid)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'mjkilian1992$default.django_site' doesn't exist")
ERROR 2016-10-01 14:05:58,158 base 1903 139774607832960 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-10-01 14:15:22,114 base 2026 140662732920704 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-10-01 14:16:09,256 base 2026 140662732920704 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-10-01 14:16:10,512 base 2026 140662732920704 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-10-01 14:20:22,171 base 2087 140280575182720 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-10-01 14:23:13,667 base 2134 139806346872704 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
ERROR 2016-10-01 14:24:31,572 base 2134 139806346872704 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 78, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.get_template(template)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/mjkilian1992/.virtualenvs/dentest-prod/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: adminplus/index.html
